#+title: Emacs Everywhere
#+author: TEC
#+date:  2021-02-06

#+html: <p><img src="https://img.shields.io/badge/Emacs-26.3-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white">
#+html: <img src="https://img.shields.io/badge/-Linux-fcc624?logo=linux&style=flat-square&logoColor=black">
#+html: <img src="https://img.shields.io/badge/-MacOS-lightgrey?logo=apple&style=flat-square&logoColor=black"></p>

A re-implementation of the fantastic idea in [[https://github.com/zachcurry/emacs-anywhere][zachcurry/emacs-anywhere]].

* Installation
** Straight

#+begin_src emacs-lisp
(use-package emacs-everywhere
  :straight (:host github
             :repo "tecosaur/emacs-everywhere"
             :files ("emacs-everywhere.el" "scripts")))
#+end_src

** Doom

#+begin_src emacs-lisp
;; $DOOMDIR/packages.el
(package! emacs-everywhere
  :recipe (:host github
           :repo "tecosaur/emacs-everywhere"
           :files ("emacs-everywhere.el" "scripts")))

;; $DOOMDIR/config.el
(when (daemonp)
  (use-package! emacs-everywhere))
#+end_src

** Dependencies

On Linux, ensure you have the following dependencies: =xclip=, =xdotool=, =xprop=, and =xwininfo=.

** Setup executable

After installing, in a new Emacs session run =M-x emacs-everywhere-install=. It will tell you
where the executable has been placed.
Have a keybinding call the executable, and that's all the setup required 🙂.

* Usage

Invoke the Emacs Everywhere executable. It will remember which window you have
focused.

A new Emacs frame will appear, within which you can type away to your heart's content.

By default, ~emacs-everywhere-insert-selection~ is a hook in
~emacs-everywhere-init-hooks~, and will insert the last text selection into your
new buffer. To clear this, type =DEL= or =C-SPC= /before anything else/.

Once you've finished and want to insert the text into the window you triggered
Emacs Everywhere from, just press =C-c C-c= or =C-x 5 0= to close the frame and
paste the content into the window (as long as ~emacs-everywhere-paste-p~ is
non-nil).

If you do /not/ wish to paste the buffer content into the original window, =C-c
C-k= still copies the content to the clipboard, but never pastes.
