#!/usr/bin/env bash

EE_APP_NAME=$( osascript \
    -e 'tell application "System Events"' \
    -e 'set frontAppName to name of first application process whose frontmost is true' \
    -e 'end tell' \
    -e 'return frontAppName' )

EE_WINDOW_TITLE=$( osascript \
    -e 'set windowTitle to ""' \
    -e 'tell application "System Events"' \
    -e 'set frontAppProcess to first application process whose frontmost is true' \
    -e 'end tell' \
    -e 'tell frontAppProcess' \
    -e 'if count of windows > 0 then' \
    -e 'set windowTitle to name of front window' \
    -e 'end if' \
    -e 'end tell' \
    -e 'return windowTitle' )

EE_TGEO=$( osascript \
    -e 'tell application "System Events"' \
    -e 'set frontWindow to front window of (first application process whose frontmost is true)' \
    -e 'set windowPosition to (get position of frontWindow)' \
    -e 'set windowSize to (get size of frontWindow)' \
    -e 'end tell' \
    -e 'return windowPosition & windowSize' )
if [ $? -ne 0 ]; then
    EE_TGEO="0, 0, 0, 0"
fi
IFS=', ' read -r -a EE_GEO <<< "$EE_TGEO"

EE_APP_NAME="\"$EE_APP_NAME\""
EA_WINDOW_ID="nil"
EE_WINDOW_TITLE="\"$EE_WINDOW_TITLE\""
EE_X="${EE_GEO[0]}"
EE_Y="${EE_GEO[1]}"
EE_WIDTH="${EE_GEO[2]}"
EE_HEIGHT="${EE_GEO[3]}"

{{call-emacs-client}}

